
# Playbook: Hosting Website

# Define the playbook, which sets up a web server hosting a website on target hosts
---
- hosts: webservers

  # Enable privilege escalation to execute tasks with elevated privileges (e.g., sudo)
  become: true

  # Define the tasks to be executed on the specified hosts
  tasks:
    # Task name: Ensure httpd (Apache) is installed
    - name: Ensure httpd (Apache) is installed

      # Use the 'yum' module to ensure the httpd package is installed
      yum:
        # Specify the name of the package to be installed (httpd)
        name: httpd
        # Specify the desired state of the package (present)
        state: present

    # Task name: Copy index.html to remote server
    - name: Copy index.html to remote server

      # Use the 'copy' module to copy the index.html file to the remote server
      copy:
        # Specify the source path of the index.html file on the control node
        src: /home/remote/index.html
        # Specify the destination path on the remote server where the file will be copied
        dest: /var/www/html/
        # Specify whether to use the source file on the control node ('yes' means 'remote_src' is enabled)
        remote_src: yes

    # Task name: Ensure httpd service is running and enabled
    - name: Ensure httpd service is running and enabled

      # Use the 'service' module to ensure the httpd service is running and enabled
      service:
        # Specify the name of the service to be managed (httpd)
        name: httpd
        # Specify the desired state of the service (started)
        state: started
        # Specify whether the service should be enabled on boot (yes)
        enabled: yes

