# Playbook: Set Passwork for Created User
---
- name: Set Password for User
  hosts: webservers
  become: true
  tasks:
    - name: Set password for user
      user:
        name: user1
        password: "{{ 'password123' | password_hash('sha512') }}"
